services:
  ea_api:
    image: ea_api
    container_name: eaapi
    build:
      context: .
      dockerfile: ProductAPI/Dockerfile
    restart: on-failure      
    ports:
      - 8001:8001
    depends_on:
      - db
    networks:
      - ea_network

  ea_webapp:
    image: ea_webapp
    container_name: eawebapp
    build:
      context: .
      dockerfile: EAWebApp/Dockerfile
    restart: on-failure      
    ports:
      - 8000:8000
    depends_on: 
      - ea_api
    networks: 
      - ea_network
  
  ea_test:
    image: ea_test
    container_name: ea_test
    build:
      context: .
      dockerfile: EATestBDD/Dockerfile
    restart: on-failure      
    depends_on:
      - ea_api
      - selenium-hub
    environment:
      - ASPNETCORE_ENVIRONMENT=remote
    networks:
      - ea_network
  
  ea_int_test:
    image: ea_int_test
    container_name: ea_integration_test
    build:
      context: .
      dockerfile: EAIntegrationTest/Dockerfile
    networks:
      - ea_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password%1#29"
      ACCEPT_EULA: "Y"
    container_name: sqlserver 
    hostname: sqlserver 
    ports:
    - "1433:1433" 
    networks:
      - ea_network
  
  chrome:
    image: selenium/node-chrome:4.38.0-20251101
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
    networks:
      - ea_network

  edge:
    image: selenium/node-edge:4.38.0-20251101
    platform: linux/amd64
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
    networks:
      - ea_network

  firefox:
    image: selenium/node-firefox:4.38.0-20251101
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
    networks:
      - ea_network

  chrome_video:
    image: selenium/video:ffmpeg-8.0-20251101
    volumes:
      - ./assets/videos:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - FILE_NAME=chrome_video.mp4
      - SE_VIDEO_FILE_NAME=auto
    networks:
      - ea_network

  edge_video:
    image: selenium/video:ffmpeg-8.0-20251101
    volumes:
      - ./assets/videos:/videos
    depends_on:
      - edge
    environment:
      - DISPLAY_CONTAINER_NAME=edge
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - FILE_NAME=edge_video.mp4
      - SE_VIDEO_FILE_NAME=auto
    networks:
      - ea_network

  firefox_video:
    image: selenium/video:ffmpeg-8.0-20251101
    volumes:
      - ./assets/videos:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - SE_NODE_GRID_URL=http://selenium-hub:4444
      - FILE_NAME=firefox_video.mp4
      - SE_VIDEO_FILE_NAME=auto
    networks:
      - ea_network

  selenium-hub:
    image: selenium/hub:4.38.0-20251101
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - ea_network

  # File browser to manage the videos from local volume
  file_browser:
    image: filebrowser/filebrowser:latest
    container_name: file_browser
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./assets/videos:/srv
    environment:
      - FB_NOAUTH=true
    networks:
      - ea_network

networks: 
   ea_network: